name: Node.js CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Connect VPS and deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/node/lessions-monitoring-system
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npx prisma generate dev
            npm run deploy